//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{

    public partial class Menu
    {
        public int Id { get; set; }
        public int MenuGrupoId { get; set; }
        public string Texto { get; set; }
        public string Enlace { get; set; }
        public string Icono { get; set; }
        public byte NuevaVentana { get; set; }
        public int Orden { get; set; }
    }
}
